package modelos;
// Generated 22/09/2019 05:13:38 PM by Hibernate Tools 4.3.1

/**
 * Espa�olFrances generated by hbm2java
 */
public class EspañolFrances implements java.io.Serializable {

    private Integer idEspFran;
    private String esp;
    private String frances;

    public EspañolFrances() {
    }

    public EspañolFrances(String esp, String frances) {
        this.esp = esp;
        this.frances = frances;
    }

    public Integer getIdEspFran() {
        return this.idEspFran;
    }

    public void setIdEspFran(Integer idEspFran) {
        this.idEspFran = idEspFran;
    }

    public String getEsp() {
        return this.esp;
    }

    public void setEsp(String esp) {
        this.esp = esp;
    }

    public String getFrances() {
        return this.frances;
    }

    public void setFrances(String frances) {
        this.frances = frances;
    }

}
